source("D:/3o\ Semestre/Calculo\ Numerico/Trabalho/lagrange.R")
source("D:/3o\ Semestre/Calculo\ Numerico/Trabalho/interpolacao-newton.R")
source("D:/3o\ Semestre/Calculo\ Numerico/Trabalho/MMQ.R")

geraY_lagrange("a1s.txt", 4,"a1s_grau4.txt")
geraY_lagrange("a1s.txt", 5,"a1s_grau5.txt")
geraY_lagrange("a1s.txt", 6,"a1s_grau6.txt")
geraY_lagrange("a1s.txt", 7,"a1s_grau7.txt")
geraY_lagrange("a1s.txt", 8,"a1s_grau8.txt")
geraY_lagrange("a1s.txt", 9,"a1s_grau9.txt")
geraY_lagrange("a1s.txt", 10,"a1s_grau10.txt")

geraY_newton("a1s.txt", 4,"a1s_grau4.txt")
geraY_newton("a1s.txt", 5,"a1s_grau5.txt")
geraY_newton("a1s.txt", 6,"a1s_grau6.txt")
geraY_newton("a1s.txt", 7,"a1s_grau7.txt")
geraY_newton("a1s.txt", 8,"a1s_grau8.txt")
geraY_newton("a1s.txt", 9,"a1s_grau9.txt")
geraY_newton("a1s.txt", 10,"a1s_grau10.txt")

##O método MMQ decidira o melhor grau, portanto passamos apenas o tamanho dos intervalos.
GeraY_MMQ("a1s.txt", 4, "(4)a1s_grau")
GeraY_MMQ("a1s.txt", 5, "(5)a1s_grau")
GeraY_MMQ("a1s.txt", 6, "(6)a1s_grau")
GeraY_MMQ("a1s.txt", 7, "(7)a1s_grau")
GeraY_MMQ("a1s.txt", 8, "(8)a1s_grau")
GeraY_MMQ("a1s.txt", 9, "(9)a1s_grau")
GeraY_MMQ("a1s.txt", 10, "(10)a1s_grau")

matrizGeradaPeloTxt <- read.table("D:/3o\ Semestre/Calculo\ Numerico/Trabalho/notas\ piano/arquivos-texto/a1s.txt")
